name: Transform tokens send from figma
on:
  repository_dispatch:
    types: [update-tokens]

jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: mkdir "tokens" directory
        run: "mkdir -p tokens"

      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.filename }}
          json: ${{ github.event.client_payload.tokens }}
          dir: "tokens"

      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Transform design tokens
        run: "pnpm i && pnpm build:tokens"

      - name: Setup Git Config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push changes
        run: |
          git add .
          git commit -m "${COMMIT_MESSAGE}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.client_payload.commitMessage || 'Tokens updated' }}
